### ISSUE TITLE
Error occured while opening an adoc file: [An internal error occurred during: "Initialize asciidoctor output". org/jruby/RubyInstanceConfig]

### ISSUE THREAD

**Issue by jiangrij** [de-jcup/eclipse-asciidoctor-editor#45]
An error dialog window occurred while opening an Adoc file in Eclipse as below:
_An internal error occurred during: "Initialize asciidoctor output". org/jruby/RubyInstanceConfig_

I have two independent Eclipse(4.7.3) in Mac, one works for asciidoctor-editor, one not.

Thanks.

**Comment by de-jcup** [comment]
Hello @jiangrij , I just released version 0.7.0 to eclipse marketplace (for details see https://github.com/de-jcup/eclipse-asciidoctor-editor/milestone/9?closed=1 )
Please try out this new version, where I made many changes. Also the loging output and the error handling was improved

If you have still such problems, please give me feedback. If all working fine with new version please close the issue.

**Comment by jiangrij** [comment]
Hi @de-jcup, thanks for your quick response. After I upgraded asciidoctor-editor to 0.7.0, the error dialog window disappeared, instead, it gave an error message as below in the document header.

> NoClassDefFoundError: org/jruby/RubyInstanceConfig
![adocplugin](https://user-images.githubusercontent.com/22519481/39356252-275d366a-4a42-11e8-8599-ffe3df2bdcbd.jpg)

Thanks.

**Comment by de-jcup** [comment]
@jiangrij : I do a sum up: 
You are
- using a mac
- eclipse 4.7.3 (oxygen 3)

### Please answer following questions:
1. Do you have the problem now with both eclipse installations or as before just with one and the other works as you mentioned before  _("I have two independent Eclipse(4.7.3) in Mac, one works for asciidoctor-editor, one not.")_
2. Which java version do you exactly use to run eclipse?
   (Please give me the version number and also which type you are using (oracle, open jdk,...)
3. Which MAC-OS are you using ?
4. Please open the error log view (if you havent the view please install the PDT (plugin development tools - so its contained). And search for log entries from Asciidoctor-Editor plugin. Maybe there is another failure before.
5. Which Eclipse are you using exactly (e.g. "Eclipse IDE for Java Developers" 4.7.3.20180405-1200)


### Please  also do following:
- open your home folder find the `.eclipse-asciidoctor-editor` folder. There is a folder `libs/1.1.0`
 please do (if you want temporarily) give permissions to execute to all of the files contained inside
 (After testing if this does solve the problem you can delete the complete folder if you like and the editor will automatically rebuild it)
- You could also try to use another java version to start eclipse.

I will try to get access to a MAC (currently I can only test with linux and windows - and those are working)

**Comment by jiangrij** [comment]
Hi @de-jcup, 
After I upgraded plugin asciidoctoreditor to 0.7.0 on the two Eclipse, still one works and one not.  The two Eclipse are now in the same version, and using the same JRE.
I also removed /home/currentuser/.eclipse-asciidoctor-editor, and restarted Eclipse, the problem persists.

**Here is my environment:**
**OS**: MacOS High Sierra 10.13.4 (17E202)
**JRE**: Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
**Eclipse**: Eclipse Java EE IDE for Web Developers. Version: Oxygen.3a Release (4.7.3a) Build id: 20180405-1200


Found the logs related to asciidoctoreditor as below, please advise, thanks.

_!ENTRY de.jcup.asciidoctoreditor 4 0 2018-04-27 15:30:01.626
!MESSAGE AsciiDoctor error occured:org/jruby/RubyInstanceConfig
!STACK 0
java.lang.NoClassDefFoundError: org/jruby/RubyInstanceConfig
	at de.jcup.asciidoctoreditor.AsciiDoctorOSGIWrapper.fetchClassLoader(AsciiDoctorOSGIWrapper.java:186)
	at de.jcup.asciidoctoreditor.AsciiDoctorOSGIWrapper.loadAsciidoctor(AsciiDoctorOSGIWrapper.java:90)
	at de.jcup.asciidoctoreditor.AsciiDoctorOSGIWrapper.getAsciidoctor(AsciiDoctorOSGIWrapper.java:80)
	at de.jcup.asciidoctoreditor.AsciiDoctorWrapper.getAsciiDoctor(AsciiDoctorWrapper.java:75)
	at de.jcup.asciidoctoreditor.AsciiDoctorWrapper.resolveAttributes(AsciiDoctorWrapper.java:164)
	at de.jcup.asciidoctoreditor.AsciiDoctorWrapper.getCachedAttributes(AsciiDoctorWrapper.java:136)
	at de.jcup.asciidoctoreditor.AsciiDoctorWrapper.resolveImagesDirPath(AsciiDoctorWrapper.java:143)
	at de.jcup.asciidoctoreditor.AsciiDoctorWrapper.convertToHTML(AsciiDoctorWrapper.java:64)
	at de.jcup.asciidoctoreditor.AsciiDoctorEditor.fullBuildTemporaryHTMLFilesAndShowAfter(AsciiDoctorEditor.java:624)
	at de.jcup.asciidoctoreditor.AsciiDoctorEditor.access$7(AsciiDoctorEditor.java:610)
	at de.jcup.asciidoctoreditor.AsciiDoctorEditor$1.run(AsciiDoctorEditor.java:795)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:182)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.ClassNotFoundException: org.jruby.RubyInstanceConfig cannot be found by de.jcup.asciidoctoreditor_0.7.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more_

**Comment by de-jcup** [comment]
Hi @jiangrij , thank you for the answers,

**My attemps to reproduce the problem**
I tried to reproduce the problem under Linux
- opened two different workspaces with "Eclipse IDE for Java Developers" Oxygen 3a with an
  updated asciidoctor-editor plugin (0.7.0)
- opened, created and changed asciidoc documents - all working
- Now downloaded complete new installation of "Eclipse Java EE IDE for Web Developers. Oxygen 3a", Eclipse Java EE IDE for Web Developers as package from eclipse.org
- After unzipping , started the Java EE IDE, and downloaded from marketplace the editor in version 0.7.0 
- after this I started the Java EE IDE twice , with workspace1 and workspace 2 and did also create, open and change asciidoc plugins - everything working fine

So with using 4 eclipse on same time, 2 different installations, with 4 workspaces everything was working fine
Java-EE IDE build info:
Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200

All was working fine.

So I am absolutely not able to reproduce the problem - at least on Linux.

**Additional thoughts**
As far as I have seen on the stacktrace above, the problem is not inside the /home/currentuser... folder structure but the classloading of the jruby instance which is settled directly inside the lib-plugin.

Hm...have no Idea why this happens... very strange.
 
**My suggestions**
- You said, one eclipse installation is working fine - and the other not
- So I suspect you are using two different workspaces...
- Please try out following: Use the working eclipse and open both workspaces with the SAME installation (when you have defined a standard workspace for startup and you do no longer have the choice to select the workspace on startup, please open your preferences and enable `"Prompt for workspace on startup"` as shown in next picture:
![image](https://user-images.githubusercontent.com/11644753/39410782-d272be8c-4bfd-11e8-813e-ec614df0bcdd.png)
- If now all is working fine and you can use the working eclipse to edit your files in both workspaces.
- But please try out also following
  - Download  https://www.eclipse.org/downloads/packages/eclipse-ide-java-ee-developers/oxygen3a
  - unzip the content
  - start the new downloaded eclipse, use some workspace und install the editor by marketplace
  - after this restart your new downloaded eclipse and try to create and open a new asciidoc file (e.g.test1.adoc)
  - if this is working, your eclipse installation which is not working with asciidoctor-editor seems to have a bug inside /strange behaviour.

**Comment by paulvi** [comment]
@jiangrij Can this be closed?

**Comment by jiangrij** [comment]
Sorry for the late response, thanks @de-jcup for kind support.
Closing this issue.
Thanks.
